### ISSUE TITLE
Export User Index to csv

### ISSUE THREAD

**Issue by poofyOwl** [master-recycler-vancouver/mrv-outreach-tracker#31]

**Comment by poofyOwl** [comment]
s this meant for facilitators, or admin only?

**Comment by poofyOwl** [comment]
Questions:
- facilitators or admin only?
- Only thing preventing other user types from exporting to csv is the lack of a button. How to restrict permissions at a lower level?
- csv filename format: "mrv-users-Y_m_d-H_M_S.csv" for entire index and "mrv-cohort-Y-users.csv" for cohorts. Is this ok? Add timestamp to cohort filename too (I thought it might be confusing)?
- fields ok? first_name, last_name, email, role, fb/insta/linkedin/twitter handles, cohort
- In users index, after exporting to CSV, the URL gets updated, so if the page gets refreshed, the save file dialog pops up again. Does it matter?

**Comment by emilymcg** [comment]
Ah just saw this. I used a low frequency email for github. Good thing I was
on here.

- facilitators and admins both allowed. if it's easier you can make it only
admins.

It's okay if individuals want to export their CSV files.

filename format is good. timestamp not required for either, since it will
be stored in the details of the downloaded file anyway.

those fields are good for the import function - for creating accounts - but
as discussed we need all outreach events for exports. which i think was a
phase 2 thing... hey? am i missing something?

- is it possible to have a confirmation message appear on the refreshed
page, so that people know it worked? it's not a big deal if not.

I'll also try to get back on github so I can answer these where they're
asked!

**Comment by poofyOwl** [comment]
Thanks for the reply! I wasn't actually expecting you to reply here, I was going to bring this up at our next scrum meeting, but this is super helpful!

About the outreach events: this specific task is just for exporting the User Index. Once I finish this feature, I will move onto exporting Outreach Events :)
